import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { ProductCart, ProductSearchList } from 'src/features'
import { Container, LayoutDefault } from 'src/components'
import { getAlgoliaClient } from 'src/lib'
import { Product } from 'src/graphql'

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const algoliaClient = getAlgoliaClient({
    index: 'dev_store',
  })

  const term = (query?.search as string) || ''
  const { hits } = await algoliaClient.search(term)

  return {
    props: {
      loading: false,
      products: hits,
    },
  }
}

export type TPageHomeProps = {
  loading?: boolean
  products: Array<Product>
}

const HomePage: NextPage<TPageHomeProps> = ({ loading, products }) => {
  const renderProductList = () => {
    if (products.length === 0) return <p>Ops! Product list is empty.</p>

    return <ProductSearchList products={products} />
  }

  return (
    <>
      <Head>
        <title>Store | The best of New York</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <LayoutDefault>
        {!loading && <Container>{renderProductList()}</Container>}
      </LayoutDefault>

      <ProductCart />
    </>
  )
}

export default HomePage
