import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import {
  Container,
  EmptyState,
  LayoutDefault,
  Pagination,
} from 'src/components'
import { ProductCart, ProductSearchList } from 'src/features/Product/components'
import { productsSearchUseCase } from 'src/features/Product/usecases'
import { Product } from 'src/graphql'

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const response = await productsSearchUseCase({ query })

  return {
    props: response,
  }
}

export type TPageSearchProps = {
  loading?: boolean
  term?: string
  products: {
    total: number
    data: Array<Product>
  }
  pages: {
    total: number
    current: number
  }
}

const SearchPage: NextPage<TPageSearchProps> = ({
  loading,
  term,
  products,
  pages,
}) => {
  const renderProductList = () => {
    if (products.total === 0)
      return (
        <Container>
          <EmptyState
            image={{
              fill: true,
              src: '/empty-search.svg',
              alt: 'Empty search illustration',
            }}
            title={`No results found for "${term}"`}
            text="We couldn't find what you searched for. Please, try searching again."
          />
        </Container>
      )

    return (
      <>
        <Container>
          <ProductSearchList
            term={term}
            total={products.total}
            products={products.data}
          />
        </Container>

        <Container>
          <Pagination total={pages.total} current={pages.current} />
        </Container>
      </>
    )
  }

  if (loading)
    return (
      <Container>
        <p>Loading...</p>
      </Container>
    )

  return (
    <>
      <Head>
        <title>Store | The best of New York</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <LayoutDefault>{renderProductList()}</LayoutDefault>

      <ProductCart />
    </>
  )
}

export default SearchPage
