import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { ProductCart, ProductSearchList } from 'src/features'
import { Container, LayoutDefault } from 'src/components'
import { getApolloClient } from 'src/lib'
import { GET_PRODUCTS_QUERY, Product, GetProductsQuery } from 'src/graphql'

export const getServerSideProps: GetServerSideProps = async () => {
  const apolloClient = getApolloClient()

  const {
    loading,
    data: { products },
  } = await apolloClient.query<GetProductsQuery>({
    query: GET_PRODUCTS_QUERY,
  })

  return {
    props: {
      loading,
      products: products,
    },
  }
}

type TPageHomeProps = {
  loading?: boolean
  products: Array<Product>
}

const Home: NextPage<TPageHomeProps> = ({ loading, products }) => {
  return (
    <>
      <Head>
        <title>Store | The best of New York</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <LayoutDefault>
        {!loading && (
          <Container>
            <ProductSearchList products={products} />
          </Container>
        )}
      </LayoutDefault>

      <ProductCart />
    </>
  )
}

export default Home
